In [1]:
pip install tensorflow


Note: you may need to restart the kernel to use updated packages.


In [1]:
!pip install tensorflow-hub


  Obtaining dependency information for tensorflow-hub from https://files.pythonhosted.org/packages/e5/50/00dba77925bf2a0a1e45d7bcf8a69a1d2534fb4bb277d9010bd148d2235e/tensorflow_hub-0.16.1-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tf-keras>=2.14.1 from https://files.pythonhosted.org/packages/19/26/ca8a6cca61f2a44f1e7ee71ebdb9c8dfbc4371f418db811cdca4641f6daa/tf_keras-2.15.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 1.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.1/1.7 MB 1.4 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.7 MB 1.5 MB/s eta 0:00:02
   ---------- ----------------------------- 0.4/1.7 MB 2.7 MB/s eta 0:00:01
   ------------- -------------------------- 0.6/1.7 MB 2.6 MB/s eta 0:00:01
   ----------------- ---------------------- 0.7/1.7 MB 2.7 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0

In [2]:
!pip install tensorflow-datasets

  Obtaining dependency information for tensorflow-datasets from https://files.pythonhosted.org/packages/fe/18/4865973f5469cfe33bbe1cfc2f1918335eb44f4cc3d316c1bce22c1af2bc/tensorflow_datasets-4.9.4-py3-none-any.whl.metadata
  Obtaining dependency information for dm-tree from https://files.pythonhosted.org/packages/e4/c1/522041457444b67125ac9527208bb3148f63d7dce0a86ffa589ec763a10e/dm_tree-0.1.8-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for etils[enp,epath,etree]>=0.9.0 from https://files.pythonhosted.org/packages/37/10/dd5b124f037a636783e416a2fe839edd7ec63c0dce7ce4f3c1da029aeb80/etils-1.7.0-py3-none-any.whl.metadata
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Obtaining dependency information for tensorflow-metadata from https://files.pythonhosted.org/packages/41/23/3705c7139886c079ef4c0e3be56a5a1fb90e9ee413a4b7caaee0ee0ea6fe/tensorflow_metadata-1.14.0-py3-none-any.whl.metadata
  Obtaining dependency i

In [3]:
!pip install numpy

In [17]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

In [7]:
train_data, validation_data, test_data = tfds.load(name="imdb_reviews",
                                                  split=('train[:60%]','train[60%:]', 'test'),
                                                  as_supervised=True)


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\HP\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteS4W1R5\imdb_reviews-train.tf…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\HP\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteS4W1R5\imdb_reviews-test.tfr…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\HP\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteS4W1R5\imdb_reviews-unsuperv…

Dataset imdb_reviews downloaded and prepared to C:\Users\HP\tensorflow_datasets\imdb_reviews\plain_text\1.0.0. Subsequent calls will reuse this data.


In [13]:
train_data
print("GPU is","available" if tf.config.experimental.list_physical_devices("GPU")else "NOT AVAILABLE")


GPU is NOT AVAILABLE


In [10]:
train_example_batch,train_labels_batch=next(iter(train_data.batch(10)))

In [20]:
train_example_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [19]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)>

In [16]:
embedding="https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer=hub.KerasLayer (embedding,input_shape=[],dtype= tf.string,trainable=True)


In [21]:
hub_layer(train_example_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

In [24]:
model =tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1))

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer_1 (KerasLayer)  (None, 20)                400020    
                                                                 
 dense (Dense)               (None, 16)                336       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 400373 (1.53 MB)
Trainable params: 400373 (1.53 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.compile(optimizer='adam',loss =tf.keras.losses.BinaryCrossentropy(from_logits=True),metrics=['accuracy'])

In [33]:
history = model.fit(train_data.shuffle(10000).batch(100), epochs = 25 ,
                 validation_data = validation_data.batch(100), verbose=1)

Epoch 1/25
150/150 [==============================] - 4s 23ms/step - loss: 0.0109 - accuracy: 0.9994 - val_loss: 0.5691 - val_accuracy: 0.8621
Epoch 2/25
150/150 [==============================] - 3s 22ms/step - loss: 0.0088 - accuracy: 0.9999 - val_loss: 0.5911 - val_accuracy: 0.8623
Epoch 3/25
150/150 [==============================] - 3s 22ms/step - loss: 0.0073 - accuracy: 0.9998 - val_loss: 0.6150 - val_accuracy: 0.8624
Epoch 4/25
150/150 [==============================] - 3s 22ms/step - loss: 0.0061 - accuracy: 0.9999 - val_loss: 0.6359 - val_accuracy: 0.8624
Epoch 5/25
150/150 [==============================] - 3s 22ms/step - loss: 0.0052 - accuracy: 0.9999 - val_loss: 0.6566 - val_accuracy: 0.8608
Epoch 6/25
150/150 [==============================] - 3s 22ms/step - loss: 0.0044 - accuracy: 0.9999 - val_loss: 0.6779 - val_accuracy: 0.8620
Epoch 7/25
150/150 [==============================] - 3s 21ms/step - loss: 0.0037 - accuracy: 0.9999 - val_loss: 0.6980 - val_accuracy: 0.8616

In [32]:
results=model.evaluate(test_data.batch(100) , verbose =2)

for name ,value in zip(model.metrics_names , results):
    print("%s: %3f"% (name,value))

250/250 - 3s - loss: 0.6127 - accuracy: 0.8436 - 3s/epoch - 11ms/step
loss: 0.612666
accuracy: 0.843560
